title: Jason Liao
description: > # this means to ignore newlines until "baseurl:"
  This is the Engineering Portfolio of Jason Liao, 
  a third year Mechatronic Systems Engineering student at SFU 
  and a team lead for the SFU Ascension Robotics club (https://ascensionrobomaster.com/)
permalink: ':title/'
baseurl: "/JasonLiaoEngiPortfolio" # the subpath of your site, e.g. /blog
url: "https://jsonx1ng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jason Liao # add your name
author-img: Jason_Liao_profpic.JPEG # add your photo
about-author: Third year Mechatronic Systems Engineering student at SFU and aspiring Roboticist # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: JsonX1ng # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
